hyperlight-dev/hyperlight

README.md

Currently, our logo doesn't show on crates.io. This is because we are using a relative path to the image. This PR changes the path of the image to be an absolute path. For more info, see: https://github.com/rust-lang/crates.io/issues/982.

[chore] Modifying logo image in README to use an absolute path

---

.github/workflows/Benchmarks.yml
.github/workflows/CreateRelease.yml
.github/workflows/dep_rust.yml
Justfile

Note: I only modified the dep_rust matrix which will run the tests to assess differences between amd and intel. In the future, we might want to consider revisiting our matrix setup.

[github-actions] Made it so tests also run on intel

---

.github/workflows/ValidatePullRequest.yml

This PR will ignore paths for markdown as well as txt files. The intent of this is to make it quicker to accept docs changes.

Ignore markdown and txt files in CI

---

.github/workflows/ValidatePullRequest.yml
.github/workflows/dep_fuzzing.yml
.github/workflows/dep_rust.yml
src/tests/rust_guests/callbackguest/Cargo.lock
src/tests/rust_guests/simpleguest/Cargo.lock

In #44, I attempted to ignore docs only CI job processing, but branch protection required jobs were still required to run. The only way to satisfy the branch protection required jobs is to have them run, but return with success. This PR does that by using conditional execution for the job rather than filtering on the PR content in the `pull_request` event handler.

Fix docs only CI job processing

---

src/hyperlight_host/src/sandbox/uninitialized.rs

When the given GuestBinary is not found, the error now includes the actual path that wasn't found. 
Also: 
- Removes a call to `try_exists`, which is unnecessary since `canonicalize` will already fail if the file doesn't exit. 
- Removes an unnecessary recreation of matched pattern for GuestBinary::Buffer.
- Converts PathBuf to String in a more ideomatic way and removes potential panic if PathBuf cannot be converted to String (i.e. not utf8 encoded)

Improve error when guest binary not found

---

.github/workflows/Benchmarks.yml
.github/workflows/dep_rust.yml

Currently, PRs are not able to compare performance to main branch, because downloading benchmarks from latest prerelease fails because the name of the artifact is incorrect. See https://github.com/hyperlight-dev/hyperlight/actions/runs/11925609379/job/33237994407#step:16:13 for an example error. 
Here is an example of it now working https://github.com/hyperlight-dev/hyperlight/actions/runs/11928115786/job/33244575940?pr=74#step:16:12. Note that some will still fail, since we haven't published benchmarks with the new naming conventions yet (It will be done as part of prerelease when this PR is merged). 
This pr also renames the matrix.hypervisor such that hyperv is used for windows, and mshv for linux

Fix 'download benchmark' workflow

---

.github/workflows/dep_rust.yml
src/hyperlight_host/src/mem/elf.rs

Switch from `.ok_or` to `.ok_or_else` do only perform the string formatting in the failing case. 
Benchmarks show that time to create an uninitialized sandbox goes from 400µs to about 330µs (-17%) on my local machine
Also adds an `amd` tag that was forgotten in PR #74

Avoid eagerly doing unnecessary string formatting

---

.github/workflows/ValidatePullRequest.yml

Pushes to the same branch/pr will cancel in-flight ValidatePullRequest jobs. The concurrency group will be something like `Validate Pull Request-refs/pull/79/merge` for pushes to a PR, and will guarantee only 1 inprogress "Validate Pull Request" job per pr.

[ci] Cancel in-progress jobs for new pushes

---

src/hyperlight_host/src/hypervisor/hypervisor_handler.rs

As per KVM docs, vCPU ioctls should be issued from the same thread that was used to create the vCPU. In accordance to that, this PR moves `set_up_hypervisor_partition` to inside the hv handler thread, which manages vCPU interactions like init and dispatching guest funciton calls.

[performance] Move `set_up_hypervisor_partition` to inside the hv handler thread

---

.github/workflows/dep_rust.yml
docs/debugging-hyperlight.md
src/hyperlight_host/Cargo.toml
src/hyperlight_host/build.rs
src/hyperlight_host/src/hypervisor/crashdump.rs
src/hyperlight_host/src/hypervisor/dump_on_crash.rs
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/hyperv_windows.rs
src/hyperlight_host/src/hypervisor/inprocess.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/hypervisor/mod.rs
src/hyperlight_host/src/lib.rs
src/hyperlight_host/src/mem/pe/pe_info.rs
src/hyperlight_host/src/sandbox/uninitialized.rs

Fixes #70. Renames the feature to just "crashdump". Moves it into VirtualCPU::run, so each driver doesn't need to call it. Behavior should be the same: dumps registers,memory_regions and raw memory to file for certain hyperlightexits: mmio, accessviolation, unknown, and errors.
Also changes uses of `crate::debug!` macro to explicilty use the `crate` module prefix to distinguish from the `log` crate.

Fix cargo feature 'dump_on_crash'

---

Cargo.lock
docs/hyperlight-metrics-logs-and-traces.md
src/hyperlight_host/Cargo.toml
src/hyperlight_host/examples/otlp_tracing/main.rs

This PR fixes the otlp_tracing example compile issues with latest opentelemetry crate.
It required a slightly different approach to set up the tracer. The [examples ](https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/examples/opentelemetry-otlp.rs) from tracing-opentelemetry crate were useful.
One other side of the problem was that `jaeger` didn't receive the traces from the example anymore and it turns out it is because of the log filtering. So, using a different `RUST_LOG` should suffice.
The new test added sets up a TcpListener that binds to the same address the tracer subscriber does so it is able to receive the traces so it can validate whether the example runs correctly

Fix otlp tracing

---

src/hyperlight_guest/build.rs
src/hyperlight_guest/src/memory.rs
src/hyperlight_host/tests/integration_test.rs
src/tests/c_guests/c_simpleguest/main.c
src/tests/rust_guests/simpleguest/src/main.rs

First commit fixes the actual bug, the second commit is rename+docs+cleanup

Fix broken realloc, rename and mark hlmalloc/hlfree/hlcalloc/hlrealloc unsafe

---

Cargo.lock
Cargo.toml
README.md
src/hyperlight_host/Cargo.toml
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/hyperv_windows.rs
src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/hypervisor/windows_hypervisor_platform.rs
src/hyperlight_host/src/sandbox/uninitialized.rs

Adds checks to ensure that when running on Windows the version of Windows is supported.
On Windows hyperlight requires the API `WHvMapGpaRange2` which only exists on Windows 11 and Windows Server 2022 (or later).
There are multiple commits in this PR each with their own description.
Fixes #76

Check that windows version is supported

---

src/hyperlight_host/scripts/apply-kvm-perf-mitigation.sh

Adds a script to mitigate for the issue #47

Adds a script for KVM perf issue mitigation on 6.x kernel

---

src/hyperlight_host/tests/sandbox_host_tests.rs

The latest KVM runner image causes the test `simple_test-parallel` to fail. The failure is due to execution time of a function call taking longer than the default maximum execution time. 
This test currently creates 100 threads to test parallel execution, and, since 100 is an arbitrary number and the test is not a scalability test this PR resolves that issue by reducing the number of threads to 50.
Note that this issue does not appear to be related to #47 (or at least applying suggested mitigations for that issue does not fix this one).
#152 opened to capture the fact that we need some scalability benchmarks

reduce number of threads in simple_test_parallel test function

---

.github/dependabot.yml

Updates dependabot in order to try and have it update `Cargo.lock` in test binaries when dependencies in `hyperlight_common` or `hyperlight_guest` have changed. 
These dependabot PRs currenlty fail  because we have a check in the PR workflow to ensure that `Cargo.lock` files are up to date as a part of any PR which works fine for most scenarios but when dependabot updates depdendencies in either `hyperlight_common` or `hyperlight_guest` this may make the `Cargo.lock` file out of date for the `simpleguest` and `callbackguest` test guest binaries.
See #148 , #162 and #161 for examples of this sort of PR
This PR was opened in response to PR feedback on #154, if this doens not work then we will re-openthat PR instead.

Update dependabot to check on test guest directories

---

Cargo.lock
src/hyperlight_host/Cargo.toml
src/hyperlight_host/src/hypervisor/surrogate_process_manager.rs
src/hyperlight_host/src/sandbox/uninitialized.rs

#144 Bump Windows from 0.58 to 0.59
#133 Bump windows-result from 0.2 to 0.3
There are a couple of API signature changes in the windows crate which are addressed in this PR.

update to latest versions of windows crates

---

Cargo.lock
Justfile
proposals/NNNN-hip-template/README.md
src/hyperlight_host/src/error.rs
src/hyperlight_host/src/func/guest_dispatch.rs
src/hyperlight_host/src/hypervisor/windows_hypervisor_platform.rs
src/hyperlight_host/src/mem/pe/pe_info.rs
src/hyperlight_host/src/sandbox/run_options.rs

% `codespell --ignore-words-list=crate,fo,habitant,wit --skip="./NOTICE.txt,./src/hyperlight_guest/third_party/*" --write-changes`
https://github.com/codespell-project/codespell

Fix typos discovered by codespell

---

.devcontainer/devcontainer.json
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/sandbox/mod.rs

These environment `KVM_SHOULD_BE_PRESENT` `HYPERV_SHOULD_BE_PRESENT` variables just add unnecessary complexity, especially for newcomers who just cloned the repo.  They're not very useful anyway

Removes requirement of specific environment variables during testing

---

src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
src/hyperlight_host/src/mem/shared_mem.rs

Previously, the code comments were not sufficiently clear as to why apparently-useless locks during the execution of the guest are necessary for the invariants of the GuestSharedMemory/HostSharedMemory split.  This led to confusion as to whether it would be a good idea to remove them, so this commit clarifies that there is a good reason for them to be there.

Add clarification on why we must take GuestSharedMemory::lock

---

.github/workflows/Benchmarks.yml
.github/workflows/dep_rust.yml
Cargo.lock
Cargo.toml
Justfile
src/hyperlight_host/Cargo.toml
src/hyperlight_host/build.rs
src/hyperlight_host/src/error.rs
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/mem/memory_region.rs

This PR adds support for Azure Linux 3.
Because there are breaking changes between version 2 and verrion 3 of the `mshv-bindings` and `mshv-ioctls` and version 2 is required for Azure Linux version 2 and version 3 is required for Azure Linux version 3, this change also includes feature flags to allow the user to specify which version of mshv to target. 
This defaults to mshv2 (Azure Linux 2), to target Azure Linux 3 enable the `mshv3` feature, there is no need to disable the mshv2 feature in this case.
CI is also updated so tests, examples and benchmarks are all run on Azure Linux 3 runners with the `mshv3` feature enabled.
Fixes https://github.com/hyperlight-dev/hyperlight/issues/167

Adds support for Azure Linux 3

---

Cargo.lock
src/hyperlight_host/Cargo.toml
src/hyperlight_host/examples/otlp_tracing/main.rs

updates open-telemetry crates to 0.27.1 and fixes breaking change
see #174 and #176 for more details

Updates to otel 0.27.1

---

.github/dependabot.yml
.github/workflows/PRLabelChecker.yml

Updates dependabot to use the `"area/dependencies"` label instead of the `"dependencies"` label for Cargo crate version updates.
Removes labels from github-actions updates, when we update release.yml for the new labels we will need to ensure that changes with no labels are excluded or add a ignore label here and then exclude that.
Updates PR Label checker job to ignore dependabot PRs

update dependabot labels

---

.github/workflows/ValidatePullRequest.yml

We have a check in the PR workflow to ensure that Cargo.lock files are up to date as a part of any PR. This works fine for most scenarios but when dependabot updates depdendencies in either `hyperlight_common` or `hyperlight_guest` this may make the Cargo.lock file out of date for the `simpleguest` and `callbackguest` test guest binaries. 
See #148 for an example of this.
This PR updates the PR workflow to update those files if there are dependabot changes to the dependencies in either of those crates.

Add a check for dependabot PR updating guest or common lib dependencies

---

Cargo.lock
src/hyperlight_host/Cargo.toml

Updates `kvm-ioctls` and `kvm-bindings` to the latest versions.
See #211 and #177

update kvm-ioctls and kvm-bindings to latest versions

---

Cargo.lock
src/hyperlight_host/Cargo.toml
src/hyperlight_host/examples/otlp_tracing/main.rs
src/hyperlight_host/src/hypervisor/surrogate_process_manager.rs
src/hyperlight_host/src/mem/layout.rs
src/hyperlight_host/src/sandbox/uninitialized_evolve.rs

See #170 
Updates the rand crate to 0.9 and fixes breaking changes

Updates rand crate to 0.9

---

src/hyperlight_host/src/sandbox/initialized_multi_use.rs
src/hyperlight_host/tests/integration_test.rs
src/tests/rust_guests/simpleguest/src/main.rs

Reset guest memory when guest function fails

---

.github/workflows/ValidatePullRequest.yml
.github/workflows/dep_rust.yml

Turns out its not so simple to update the test rust guests Cargo.lock file so dependabots PRs dont fail when common crates have dependency updates (as #227 and #154 tried to do) , it can be done but would be error prone and messy so rather than do that this PR removes the enforcement of Cargo.lock being up to date for the test rust guests and reverts the changes from those prior PRs.
Once this merges it should be possible to recreate the PRs #210 #212 and #229 and they should then pass status checks

Dont check cargo lock for Rust test guest

---

src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
src/hyperlight_host/src/mem/shared_mem.rs

#135 introduced a change to the way memory is allocated and shared with surrogate process on Windows, this change causes failures when the `inprocess` feature is enabled , tests failed but did not trigger CI failures because of #138 .
This PR fixes that issue.

Fix issues with using `CreateMapViewOfFile` with `inprocess` feature

---

.github/workflows/dep_rust.yml
Justfile

Fixes #138
Somehow pwsh won't always fail the job if a step fail.
This PR cannot merge until the tests are passing

Fix CI passing with failing tests

---

src/hyperlight_host/benches/benchmarks.rs

Seems like typos has suddenly started to detect some spelling mistakes causing all PR validation to fail:
https://github.com/hyperlight-dev/hyperlight/actions/runs/13360849747/job/37310265017
This PR should fix that

Fix typos that are causing all PRs to fail CI

---

.github/workflows/ValidatePullRequest.yml

Fixes typos to a specific version to prevent new spell check failures when main branch is updated

Fix typos version

---

.gitignore
.vscode/settings.json

#66 removed .vscode/settings.json and .vscode/launch.json. After some thinking, I think we removed a bit too much in that PR.
This PR adds back a minimal settings.json, which makes rust-analyzer work with simpleguest and callbackguest. Importantly, the setting should have no impact on users not using vscode. If anyone has a strong opinion why we should NOT check-in this file, please let me know.

add back minimal vscode settings file for rust-analyzer

---

src/tests/rust_guests/callbackguest/Cargo.lock
src/tests/rust_guests/simpleguest/Cargo.lock

After the dependabot bump of strum from 0.27.0 to 0.27.1, the rust_tests Cargo.lock show as modified locally.

update the tests Cargo.lock to reflect dependabot change

---

.github/workflows/dep_rust.yml
Cargo.lock
Justfile
docs/README.md
docs/how-to-debug-a-hyperlight-guest.md
src/hyperlight_host/Cargo.toml
src/hyperlight_host/build.rs
src/hyperlight_host/examples/guest-debugging/main.rs
src/hyperlight_host/src/error.rs
src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
src/hyperlight_host/src/hypervisor/gdb/mod.rs
src/hyperlight_host/src/hypervisor/gdb/x86_64_target.rs
src/hyperlight_host/src/hypervisor/handlers.rs
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/hyperv_windows.rs
src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
src/hyperlight_host/src/hypervisor/inprocess.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/hypervisor/mod.rs
src/hyperlight_host/src/mem/layout.rs
src/hyperlight_host/src/mem/shared_mem.rs
src/hyperlight_host/src/sandbox/config.rs
src/hyperlight_host/src/sandbox/mem_access.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/src/sandbox/uninitialized_evolve.rs

The current implementation supports:
- add/remove HW breakpoints (max 4)
- add/remove SW breakpoints
- read/write registers
- read/write addresses
- step/continue
- get code offset from target
The overall architecture is designed to work like a `Request - Response` protocol from the gdb thread to the hypervisor handler over a `DebugCommChannel`.
- All the functionality is implemented on the hypervisor side so it has access to the shared memory and VcpuFd
- The gdb thread uses `gdbstub` to handle the communication with the gdb client
- when the gdb client requests the supported features mentioned above, a request is sent forward to the hypervisor handler for the running sandbox to run

Add support for Hyperlight KVM guest debugging using gdb 

---

Cargo.lock
Cargo.toml
src/tests/rust_guests/callbackguest/Cargo.lock
src/tests/rust_guests/simpleguest/Cargo.lock

Prepare for 0.2.0 release. I'll manually edit the release notes this release in case they are messed up. I'll fix up release-notes automation after the release.

Bump hyperlight version to 0.2.0

---

src/hyperlight_host/Cargo.toml

Fixes `mshv` crates to version 0.3.2 as version 0.3.3 causes failures in CI.

Fix mshv crates version to 0.3.2

---

src/hyperlight_common/src/flatbuffer_wrappers/util.rs
src/hyperlight_guest/src/host_function_call.rs
src/hyperlight_guest_capi/src/flatbuffer.rs
src/tests/rust_guests/callbackguest/src/main.rs
src/tests/rust_guests/simpleguest/src/main.rs

Makes `get_flatbuffer_result` and `get_host_value_return_as` generic, see 2 commits.

Generic guest/host result API

---

.github/workflows/dep_rust.yml
Justfile
src/hyperlight_guest/src/guest_function_call.rs
src/hyperlight_guest/src/guest_function_definition.rs
src/hyperlight_guest_capi/src/dispatch.rs
src/tests/rust_guests/callbackguest/src/main.rs
src/tests/rust_guests/simpleguest/src/main.rs

closes #217 by running cargo clippy on the guests in CI. Also fixes existing clippy violations that have snuck in. Note that the change from i64->usize is a breaking change
also closes #216

Run clippy on guests in CI

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This installs `gdb`  and `C/C++ Extension pack` for a better experience debugging in a devcontainer either locally or in Github Codespaces.
Not having these installed means the user needs to do it every time the container gets started

devcontainer: install gdb and vscode ext for debugging

---

.github/workflows/dep_rust.yml

Rustup 1.28.0 stopped implicitly downloading the toolchain in `rust-toolchain.toml` by default (if it is not already installed when you install specific targets), so we'll need to add it explicitly. Note that it's important we download nightly first, and then 1.81, so that 1.81 is left as the default.

Fix CI rust toolchain

---

.github/workflows/ValidatePullRequest.yml

This is needed because gating on specific skippable jobs does not work when those jobs are skipped (for example during docs-only PRs). Inspired by wasmtime's main.yml ci job
See https://github.com/hyperlight-dev/hyperlight/pull/334 for an docs-only PR where this happened.

Add a specific CI job on which we can gate PRs. 

---

.github/workflows/Fuzzing.yml
.github/workflows/ValidatePullRequest.yml
Justfile
fuzz/Cargo.toml
fuzz/README.md
fuzz/fuzz_targets/guest_call.rs
fuzz/fuzz_targets/host_call.rs
fuzz/fuzz_targets/host_print.rs
src/hyperlight_testing/src/lib.rs

Some fuzzing scenarios we want to report require building a fuzzing binary with `cargo fuzz build` and submitting that binary to a fuzzing harness. In those instances we also want to submit a guestbinary and this PR makes sure that the guestbinary can be found in the same directory as the fuzzing binary.

Update fuzzing test to check for simpleguest in same directory as executable

---

.github/workflows/CreateRelease.yml

The release workflow broke by #301 because I didn't update the CreateRelease.yml to take into account the new required parameters. Instead of fixing it, I'm removing the fuzzing from the release workflow, because we shouldn't fuzz in the release job anyway.

Fix release workflow

---

docs/how-to-debug-a-hyperlight-guest.md

Add information about how to setup VSCode guest debugging using CodeLLDB extension

dbg: update guest debugging docs to explain how to use lldb in vscode

---

Justfile

Increase fuzzing memory limit required by address sanitization, and enable sanitizer for build-fuzzer recipe

Increase fuzzing memory limit

---

.github/workflows/Benchmarks.yml
.github/workflows/CargoPublish.yml
.github/workflows/CreateRelease.yml
.github/workflows/dep_build_guest_binaries.yml
.github/workflows/dep_fuzzing.yml
.github/workflows/dep_rust.yml

Fixes https://github.com/hyperlight-dev/hyperlight/issues/165

Using ci-workflow-setup@v1.3.0 to use clang18 on Ubuntu runners

---

README.md

This PR updates the readme to add details for joining the CNCF Slack and points to the #hyperlight channel.

readme update for Slack details to point to CNCF #hyperlight

---

Cargo.toml
src/hyperlight_host/Cargo.toml

Removes unused dependecy, and cleans up workspace cargo.toml slightly.
For the Cargo.toml changes, common, guest,host, testing are already included as workspace path dependencies, making them members already.
No crates depend on hyperlight_guest_capi nor fuzz, so they stay regular members

Remove unused cargo dependency and cleanup workspace cargo.toml

---

.github/release.yml
docs/github-labels.md

Documents the meaning of github labels and issue types, ~~and changes automatic release notes to be just 2 categories.~~
The release notes will now be manually edited as described in #348

Document label meaning

---

src/hyperlight_common/src/clippy.toml
src/hyperlight_common/src/lib.rs
src/hyperlight_host/src/clippy.toml
src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
src/hyperlight_host/src/hypervisor/surrogate_process_manager.rs
src/hyperlight_host/src/hypervisor/windows_hypervisor_platform.rs
src/hyperlight_host/src/lib.rs
src/hyperlight_host/src/mem/elf.rs
src/hyperlight_host/src/mem/loaded_lib.rs
src/hyperlight_host/src/mem/memory_region.rs
src/hyperlight_host/src/mem/mgr.rs
src/hyperlight_host/src/mem/pe/base_relocations.rs
src/hyperlight_host/src/mem/pe/pe_info.rs
src/hyperlight_host/src/mem/shared_mem.rs
src/hyperlight_host/src/metrics/int_gauge_vec.rs
src/hyperlight_host/src/metrics/mod.rs
src/hyperlight_host/src/sandbox/outb.rs
src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
src/hyperlight_host/src/sandbox_state/sandbox.rs
src/hyperlight_host/src/seccomp/guest.rs

This PR:
Adds a clippy lints to check for use of expect, panic and unwrap in hyperlight-host for non test/non dev code in hyperlight_host and hyperlight_common
Removes all uses of expect in non test/dev code in hyperlight-host.
Removes all uses of panic in non test/dev code in hyperlight-host.
Removes all uses of unwrap in non test/dev code in hyperlight-host.
Adds a clippy.toml file to hyperlight_host/src and hyperlight_common/src to prevent the use of assert* using disallowed_macros lint
Disables the disallowed_macros lint for test and dev code
Fixes #320

Review/remove and prevent unintentional use of `expect/assert*/panic/unwrap` in hyperlight_host and hyperlght_common

---

.github/workflows/CreateRelease.yml

This change allows extract-changelog.sh to run, which is used for creating release notes, which was introduced in #348.
The release job is currently failing, see https://github.com/hyperlight-dev/hyperlight/actions/runs/13932381161/job/38993460531
gh-cli is already included in the ubuntu image so removing that step

Switch release job to use linux runner

---

.github/workflows/CreateRelease.yml

Fixes the tarfiles of our benchmarking artifacts to match the ones that we create. When switching to linux runners in #370, this became a hard-errror: https://github.com/hyperlight-dev/hyperlight/actions/runs/13954211641/job/39062218141

Fix benchmark artifact names in release job

---

.github/workflows/CreateRelease.yml

I typoed in #371 unfortunately: https://github.com/hyperlight-dev/hyperlight/actions/runs/13956374020/job/39069810365

Fix filename typo in release workflow

---

.github/dependabot.yml

Makes sure the correct label is applied to GH actions dependabot PRs

Fixes label for GH action updates

---

.github/workflows/dep_rust.yml
Justfile
docs/debugging-hyperlight.md
docs/how-to-debug-a-hyperlight-guest.md
src/hyperlight_host/build.rs
src/hyperlight_host/examples/guest-debugging/main.rs
src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
src/hyperlight_host/src/hypervisor/gdb/kvm_debug.rs
src/hyperlight_host/src/hypervisor/gdb/mod.rs
src/hyperlight_host/src/hypervisor/gdb/mshv_debug.rs
src/hyperlight_host/src/hypervisor/gdb/x86_64_target.rs
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
src/hyperlight_host/src/hypervisor/kvm.rs

This PR address the #220 issue.
Additionally, the first 7 commits refactor the existing guest debugging code and moves code from `kvm.rs` to a new file that is to contain the hypervisor specific debugging functionality.

Gdb support for mshv guests

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Changes in preparation of v0.3.0 release of Hyperlight..
Includes:
- changes in `Cargo.toml` and `Cargo.lock`
- updates in `CHANGELOG.md` to specify major changes apart from the generated list of merged PRs.

release: change crate version to v0.3.0 and update CHANGELOG.md

---

src/tests/rust_guests/callbackguest/Cargo.lock
src/tests/rust_guests/simpleguest/Cargo.lock

This PR updates the rust tests dependencies of the new Hyperlight crate version

release: update rust tests deps to latest hyperlight version

---

CHANGELOG.md

This fixes the hyperlight `CHANGELOG.md` file to correctly point `v0.3.0` to the comparison link between the `v0.3.0..v0.2.0`.
Also this is a dependency for the release pipeline that generates the changelog for a new release.

changelog: fix version typo

---

.github/dependabot.yml
Cargo.toml

Reverses a change that was made to the package level Cargo.toml in #360 which has caused dependabot to fail with `unknown_error`, see [here](https://github.com/hyperlight-dev/hyperlight/actions/runs/14299164915/job/40070585565) for an example. 
I do not know why this change caused the error but I have verified that it works locally using the dependabot cli.
Also updates the number of Open PRs allowed to 40, so we can catch up with the missing version updates in one go.

Fix dependabot

---

.github/dependabot.yml

Additional updates to dependabot to exclude test guests and mshv crates which both cause errors with update job

Fix dependabot for issues with test guests and mshv crates

---

src/hyperlight_host/src/hypervisor/hypervisor_handler.rs

Fixes #373
`Running` atomic must be set from the main thread, not the hypervisor-thread itself.
See details of the issue for more info

Fix racecondition in hypervisor-handler thread

---

docs/hyperlight-metrics-logs-and-traces.md
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/hyperv_windows.rs
src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
src/hyperlight_host/src/hypervisor/inprocess.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/hypervisor/mod.rs
src/hyperlight_host/src/sandbox/outb.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
src/hyperlight_host/tests/integration_test.rs
src/hyperlight_testing/src/logger.rs
src/hyperlight_testing/src/simplelogger.rs

Allow explicit setting of max guest log level, , if this is not set check `RUST_LOG` environment variable.
The guest log level impacts the amount of logs produced by the guest, its presently set by examining the value of max_log_level in the host.
This may not be appropriate since logging in the guest is expensive and it may cause logs to be emitted from the guest but ignored in the host. This change introduces a function on an `UninitializedSandbox` to set the level explicitly, if this is not set the env var `RUST_LOG` is parsed to determine the log level so that logs  are only produced if they are going to be consumed.  If `RUST_LOG` is not set then the max guest log level is set to error.
Updates inconsistent crate name `hyperlight-guest` in guest logs to `hyperlight_guest`

Fix issues in guest logging

---

.github/workflows/IssueLabelChecker.yml

At some point, the needs review label was renamed from `lifecycle/needs review` to `lifecycle/needs-review`.

Fix issue label checker

---

.github/dependabot.yml
.github/workflows/auto-merge-dependabot.yml
dev/auto-approve-dependabot.sh

Issue #299 suggested batching GH PRs to cut down the overhead of dealing with them, a large part of that overhead is caused by having to review/approve/merge each request alongside the impact of updates to main making it hard to merge other PRs (because of the way we need to merge due to other GH issues).
This PR attempts to solve these issues by automating the process of approval and merging of dependabot PRs, and doing it at a time when there should be less merging of "real" PRs taking place. It does the following:
Runs the dependabot job at 03:00 UTC.
Runs a new job at 04:00 UTC, this job runs a script which checks for any open PRs authored by dependabot, or each one it finds it checks the following:
That the PR only modifies Cargo.lock/Cargo.toml or GH actions workflows.
No status …

Add GH job and script to auto approve dependabot PRs.

---

.github/workflows/auto-merge-dependabot.yml
dev/auto-approve-dependabot.sh

The implementation of the script that automatically approves dependabot PRs relied on issuing commands to dependabot by using comments in the PR such as `@dependabot merge` , this result in a comment in the PR `Sorry, only users with push access can use that command.` 
I attempted to fix this by creating a GitHub App, giving it the correct permissions and then [using an app installation token in the workflow](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow) , however this did not work either as it turns out that dependabot checks to see if the token belongs to a real user with push access to the repo when these commands are issued.
I resolved the issue by setting auto …

Update dependabot autocommit script and job

---

c.just

I ran into an issue running `just guests` on Fedora 41, and adding the -fPIC option in the C flags fixes this.
Please let me know if I need to make any changes to this PR. Thank you.

fix: Add -fPIC option for building C guests.

---

src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/hypervisor/windows_hypervisor_platform.rs
src/tests/rust_guests/callbackguest/Cargo.lock
src/tests/rust_guests/simpleguest/Cargo.lock

When checking if a specific hypervisor is present using for example `kvm::is_hypervisor_present`, and the hypervisor is not present, a log message is printed with the word 'Error' in it, which was confusing since it's not actually an error.
The second commit does a slight cleanup by switching to Mshv::new() to avoid having to manually close the fd with raw libc calls.
Closes #379

Fix confusing log message when checking present hypervisor

---

.github/workflows/dep_rust.yml
Justfile
src/hyperlight_common/Cargo.toml
src/hyperlight_host/examples/guest-debugging/main.rs
src/hyperlight_host/examples/logging/main.rs
src/hyperlight_host/examples/tracing/main.rs
src/hyperlight_testing/Cargo.toml

First commit:
- Renames the just recipe for testing to `test` (instead of `test-rust`) and for building to `build` (instead of `build-rust`)
- Reorders the justfile after category: building, testing, linting, rust-examples, artifacts, benchmarks, fuzzing, flatbuffrers
- Modifies several crates' cargo.toml to set `doctest=false`, so that `cargo test` doesn't show noise (running 0 tests)
- Removes the need to set environment variables for certain rust examples/tests
Second commit:
- fixes a bug where the gdb test failed if the terminal size was too small (due to pagination).

Clean up justfile and testing

---

.gitignore
Justfile
docs/paging-development-notes.md
src/hyperlight_host/src/lib.rs
src/hyperlight_host/src/mem/layout.rs
src/hyperlight_host/src/mem/mgr.rs
src/hyperlight_host/src/mem/ptr.rs

This PR is the start of an effort to break down #297 into more digestible pieces. 
In here, I changed the base address from our arbitrary 0x200_000 value start to 0x0, which is needed for custom guests (e.g., Nanvix) to execute properly. Aside from just changing the value, I also had to modify our `get_address` macro and the PT setup–see efecff4.
In addition, I also committed two small convenience things: (1) added the .gdbinit to our .gitignore, and (2) added a new Justfile recipe to more easily run a CI-like test suite locally.

Change base address from 0x200_000 to 0x0

---

.github/workflows/CreateRelease.yml

Without it, our release notes generation does not work properly, as seen here for v0.4.0 release https://github.com/hyperlight-dev/hyperlight/actions/runs/14764756314/job/41454523267#step:12:12, so I had to run it locally and update the release notes manually.

Add GH_TOKEN env to release workflow

---

src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/mem/layout.rs
src/hyperlight_host/src/mem/memory_region.rs
src/hyperlight_host/src/mem/mgr.rs

These memory regions are unused and should be removed.
> Note: Just like #450 , this PR is also part of the effort of breaking #297 into more digestible bits.

Remove kernel stack and boot stack memory regions

---

src/hyperlight_host/benches/benchmarks.rs
src/tests/rust_guests/simpleguest/src/main.rs

Adds a benchmark which calls a guest function with two large parameters (string and vec). This makes it easier to profile our guest function calling (specifically (de-)serialization of parameters) and to locate unnecessary copies/clones

Add benchmark for guest call with large parameters

---

src/hyperlight_host/src/hypervisor/surrogate_process_manager.rs

MapViewOfFileNuma2  has started failing sometimes in CI. This PR adds some more information to the error message to help us debug the issue.

Add error logging when MapViewOfFileNuma2 fails

---

src/hyperlight_common/src/mem/mod.rs
src/hyperlight_guest/src/entrypoint.rs
src/hyperlight_guest/src/guest_error.rs
src/hyperlight_guest/src/guest_function_call.rs
src/hyperlight_host/src/func/guest_err.rs
src/hyperlight_host/src/mem/layout.rs
src/hyperlight_host/src/mem/memory_region.rs
src/hyperlight_host/src/mem/mgr.rs
src/hyperlight_host/src/sandbox/config.rs
src/hyperlight_host/src/sandbox/uninitialized.rs

Removed the guest error region. Now, instead, we use the input/output data stacks to transmit guest errors.
> Note: Just like #457 , this PR is also part of the effort of breaking #297 into more digestible bits.

Guest error region refactor

---

src/hyperlight_host/benches/benchmarks.rs
src/hyperlight_host/examples/guest-debugging/main.rs
src/hyperlight_host/examples/hello-world/main.rs
src/hyperlight_host/src/func/guest_dispatch.rs
src/hyperlight_host/src/func/host_functions.rs
src/hyperlight_host/src/func/mod.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/tests/common/mod.rs
src/hyperlight_host/tests/sandbox_host_tests.rs

This PR removes the HostFunctionXX traits, and replaces them with a single HostFunction trait.

Unify HostFunctionXX traits into a single HostFunction

---

Cargo.lock
src/hyperlight_host/Cargo.toml
src/hyperlight_host/src/mem/layout.rs

This PR removes the last usage of the `paste` crate.
Fixes #341

Remove dependency on the paste crate

---

README.md
src/hyperlight_host/benches/benchmarks.rs
src/hyperlight_host/examples/guest-debugging/main.rs
src/hyperlight_host/examples/hello-world/main.rs
src/hyperlight_host/src/func/guest_dispatch.rs
src/hyperlight_host/src/func/host_functions.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/tests/sandbox_host_tests.rs

This PR adds the `register` and `register_with_extra_allowed_syscalls` methods to the `UninitializedSandbox` to register host methods.
e.g.,
```rust
uninitialized_sandbox.register("add", |a: i32, b: i32| {
Ok(a + b)
})?;
```
This method accepts either:
* `FnMut(..) -> Result<R>`
* `Arc<Mutex<FnMut(..) -> Result<R>>>`
* `&Arc<Mutex<FnMut(..) -> Result<R>>>`
This is controlled by the IntoHostFunction trait.
This is not a breaking change. It's an additive change, and the previous registration mechanism continues to works.

Improve the ergonomics of registering host functions

---

src/hyperlight_host/src/func/host_functions.rs
src/hyperlight_host/src/func/param_type.rs
src/hyperlight_host/src/func/ret_type.rs

As far as I can tell those generics are not needed
They also mean that for each generic value it's actually a different trait, making it harder to use them as generics themselves.

Remove generics from SupportedParameterType and SupportedReturnType traits

---

src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs
src/hyperlight_host/src/func/host_functions.rs
src/hyperlight_host/src/func/param_type.rs
src/hyperlight_host/src/func/ret_type.rs

This PR:
* reduces code duplication using macros
* replaces `get_hyperlight_type` with a `TYPE` associated const
* replaces `get_hyperlight_value(&self)` with `into_value(self)`, for a better name and avoiding a copy.
* replaces `get_inner(v: XxxValue)` with `from_value(v: XxxValue)`, for a better name.

Improve ergonomics of SupportedParameterType and SupportedReturnType

---

src/hyperlight_host/src/hypervisor/gdb/arch.rs
src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
src/hyperlight_host/src/hypervisor/gdb/kvm_debug.rs
src/hyperlight_host/src/hypervisor/gdb/mod.rs
src/hyperlight_host/src/hypervisor/gdb/mshv_debug.rs
src/hyperlight_host/src/hypervisor/hyperv_linux.rs

I opened up this PR to address some leftover comments from a previous PR.
This closes #380 .
These changes do the following
- move the x86 vCPU specific constants to `gdb/arch.rs` to avoid duplicating them
- add a function that determines the vCPU stop reason based on a series of parameters (DR6 register, exception vector)
- modify kvm `get_stop_reason` method to use the hypervisor independent function described above 
- retrieve additional information from the mshv `hv_message` returned after a `run` call.
This information serves the `get_stop_reason` with information on the exception that was triggered.
- modify the mshv debugging code to use the hypervisor independent function which determines the stop reason of an x86 vCPU.
Note: I tested the scenario specified in [this …

Gdb debug improvements

---

src/hyperlight_host/src/func/host_functions.rs
src/hyperlight_host/src/sandbox/host_funcs.rs
src/hyperlight_host/src/sandbox/mod.rs

The `FunctionDefinition` struct is unused and can be simple removed.
The `FunctionsMap` struct is just a thin wrapper around a `HashMap` that re-exposes the same API, so it can also be removed.

Remove unused FunctionDefinition and redundant FunctionsMap

---

src/hyperlight_host/src/sandbox/host_funcs.rs
src/hyperlight_host/src/sandbox/initialized_multi_use.rs
src/hyperlight_host/src/sandbox/outb.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
src/hyperlight_host/src/seccomp/guest.rs

This PR is a continuation of #479. I'll keep this PR in draft until #479 is merged.
The new changes in this PR (excluding #479) are here:
https://github.com/jprendes/hyperlight/compare/host_function_2...jprendes:hyperlight:host_function_3

Refactor HostFuncsWrapper

---

README.md
fuzz/fuzz_targets/guest_call.rs
fuzz/fuzz_targets/host_call.rs
fuzz/fuzz_targets/host_print.rs
src/hyperlight_host/benches/benchmarks.rs
src/hyperlight_host/examples/func_ctx/main.rs
src/hyperlight_host/examples/guest-debugging/main.rs
src/hyperlight_host/examples/hello-world/main.rs
src/hyperlight_host/examples/logging/main.rs
src/hyperlight_host/examples/metrics/main.rs
src/hyperlight_host/examples/tracing-chrome/main.rs
src/hyperlight_host/examples/tracing-otlp/main.rs
src/hyperlight_host/examples/tracing-tracy/main.rs
src/hyperlight_host/examples/tracing/main.rs
src/hyperlight_host/src/func/call_ctx.rs
src/hyperlight_host/src/func/guest_dispatch.rs
src/hyperlight_host/src/func/host_functions.rs
src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
src/hyperlight_host/src/hypervisor/mod.rs
src/hyperlight_host/src/metrics/mod.rs
src/hyperlight_host/src/sandbox/initialized_multi_use.rs
src/hyperlight_host/src/sandbox/mod.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
src/hyperlight_host/tests/common/mod.rs
src/hyperlight_host/tests/integration_test.rs
src/hyperlight_host/tests/sandbox_host_tests.rs

With #480 merged, registering a host function with a name that is already in use, just replaces the previous registration.
This means that we can pre-emptively register the default `HostPrint` method, and replace it afterwards.
This PR removes `host_print_writer` from the arguments to `UninitializedSandbox::new`.
The default host print is pre-emptively registered, and a new `HostPrint` can be registered like any other host function.
Alternatively, the method `register_print` can be used, which uses the correct name and (compile-time-)checks the function signature.
This partly addresses the following comment (i.e., it still doesn't implement a builder pattern, but does allow adding extra syscalls to the writer method)
https://github.com/hyperlight-dev/hyperlight/blob/a862d4ad73c72ab89e4504f …

Remove `host_print_writer` from the arguments to `UninitializedSandbox::new`

---

Justfile
src/hyperlight_common/src/mem.rs
src/hyperlight_guest/src/entrypoint.rs
src/hyperlight_guest/src/host_function_call.rs
src/hyperlight_guest/src/interrupt_handlers.rs
src/hyperlight_guest/src/lib.rs
src/hyperlight_host/Cargo.toml
src/hyperlight_host/build.rs
src/hyperlight_host/src/hypervisor/handlers.rs
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/hyperv_windows.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/lib.rs
src/hyperlight_host/src/sandbox/mem_mgr.rs
src/hyperlight_host/src/sandbox/outb.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/src/testing/log_values.rs
src/hyperlight_host/tests/integration_test.rs
src/tests/rust_guests/callbackguest/src/main.rs

In #474, I removed the guest panic context region. With that, aborting was split into two steps:
(1) printing panic info w/ debug_print, and
(2) exiting w/ abort and codes.
This PR addresses feedback I got in #474 to join the operations by buffering string output when aborting.
This PR also cleans up our manual chunking logic w/ outb and leverages out8, out16, and out32 to minimize VM exits. Abort detects it should finishing buffering by a terminator code (0xFF).
Edited tests to check for panic message in aborts as they were prior to #474 merged.
This PR can be reviewed commit by commit. I also made some other minor changes like:
- removing some legacy unused structs, and
-  adding a feature flag to logging some of our build metadata, which uses a git2 dependency that is not available on …

Bring back panic info to abort

---

src/hyperlight_host/src/func/host_functions.rs
src/hyperlight_host/src/func/mod.rs
src/hyperlight_host/src/func/param_type.rs
src/hyperlight_host/src/func/ret_type.rs
src/hyperlight_host/src/func/utils.rs
src/hyperlight_host/src/sandbox/host_funcs.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/tests/common/mod.rs
src/hyperlight_host/tests/sandbox_host_tests.rs

Some more refactor of `HostFunction`.
In this PR:
* the registration can't be made from the function anymore, and has to be done from the sandbox.
* the registered function can return either the plain type `T`, or a `Result<T>`.
* adds a new `ParameterTuple` trait that is used to define serializable input to a function.

Refactor HostFunction

---

src/hyperlight_guest/build.rs

This incorrect statment (leftover by accident from #499) caused hyperlight-guest to always be recompiled, even with no new changes (SLOW!). This made commands such as `just rg` and  `just guests` always rebuild hyperlight-guest (sometimes several times over).
```
Dirty hyperlight-guest v0.4.0 (/home/ludde/hyperlight-new/src/hyperlight_guest): the file `/home/ludde/hyperlight-new/src/hyperlight_guest/include` is missing
...
Dirty simpleguest v0.4.0 (/home/ludde/hyperlight-new/src/tests/rust_guests/simpleguest): the dependency hyperlight_guest was rebuilt
```
Closes #508

Prevent hyperlight_guest from always rebuilding even with no new updates

---

.github/copilot-instructions.md

The path to github-labels.md has a comma instead of a period before the extension.
Also removed some extra spaces between words or at ends of lines.

Fix typo in path to docs/github-labels.md

---

.github/copilot-instructions.md

Update the copilot instructions so that copilot both gpg-signs and signs-off commits.

Make sure copilot gpg signs and signs-off commits

---

src/hyperlight_common/src/mem.rs
src/hyperlight_guest/src/entrypoint.rs
src/hyperlight_guest/src/shared_input_data.rs
src/hyperlight_guest/src/shared_output_data.rs
src/hyperlight_host/src/lib.rs
src/hyperlight_host/src/mem/layout.rs

This PR changes our pointer usage in the guest and common lib to be portable (i.e., using `u64s` instead of `usize` or pointer types that vary between architectures).
Plus, I did some general housekeeping like removing legacy fields/comments, refactored the PEB structs to avoid code duplication, and madeour PEB related struct items snake case.
Reviews can be made commit-by-commit, if you preferred.

Make common and guest libs portable

---

src/hyperlight_guest/third_party/musl/arch/x86_64/bits/setjmp.h
src/hyperlight_host/Cargo.toml
src/hyperlight_host/src/error.rs

This PR fixes up a couple of changes in this version of hyperlight which are breaking changes to `hyperlight-js`:
[Add JsonConversionFailure back as it used by hyperlight-js](https://github.com/hyperlight-dev/hyperlight/commit/9b68df50bdb876d8565908a0c5b510d7b6f2519e)
[Add missing musl arch specific setjmp.h file](https://github.com/hyperlight-dev/hyperlight/commit/11cf7fdc289a3ff26fa16af440592ac30359dcb8)

Fix breaking changes for hyperlight js

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/tests/rust_guests/callbackguest/Cargo.lock
src/tests/rust_guests/simpleguest/Cargo.lock

As discussed in today's community meeting.  Following instructions for release in https://github.com/hyperlight-dev/hyperlight/blob/main/docs/how-to-make-releases.md

Prepare for v0.5.0 release

---

README.md
fuzz/fuzz_targets/guest_call.rs
fuzz/fuzz_targets/host_call.rs
fuzz/fuzz_targets/host_print.rs
src/hyperlight_host/benches/benchmarks.rs
src/hyperlight_host/examples/func_ctx/main.rs
src/hyperlight_host/examples/guest-debugging/main.rs
src/hyperlight_host/examples/hello-world/main.rs
src/hyperlight_host/examples/logging/main.rs
src/hyperlight_host/examples/metrics/main.rs
src/hyperlight_host/examples/tracing-chrome/main.rs
src/hyperlight_host/examples/tracing-otlp/main.rs
src/hyperlight_host/examples/tracing-tracy/main.rs
src/hyperlight_host/examples/tracing/main.rs
src/hyperlight_host/src/func/call_ctx.rs
src/hyperlight_host/src/func/guest_dispatch.rs
src/hyperlight_host/src/func/param_type.rs
src/hyperlight_host/src/func/ret_type.rs
src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
src/hyperlight_host/src/metrics/mod.rs
src/hyperlight_host/src/sandbox/host_funcs.rs
src/hyperlight_host/src/sandbox/initialized_multi_use.rs
src/hyperlight_host/src/seccomp/guest.rs
src/hyperlight_host/tests/integration_test.rs
src/hyperlight_host/tests/sandbox_host_tests.rs

This PR changes the signature of `MultiUseSandbox::call_guest_function_by_name` and `MultiUseGuestCallContext::call` to use native Rust types instead of using `ParamerValue` and `ReturnValue`.

Use native types when calling host functions

---

Cargo.lock
src/hyperlight_host/Cargo.toml

Updates `kvm-ioctls` crate to version 0.22 and `kvm-bindings` crate to version 0.12

Update kvm-ioctls crate  to 0.22 and kvm-bindings crate to 0.12

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/tests/rust_guests/callbackguest/Cargo.lock
src/tests/rust_guests/simpleguest/Cargo.lock

This commit was (incorrectly) only made to `release/v0.5.1` branch. Adds it here to main as well so everything is sync.

Bump version to 0.5.1 and add changelog

---

README.md
rust-toolchain.toml

Automatically installs the guest cross-compilation target if not installed.
Should at least help alleviate some potential friction when getting started with hyperlight.
Tested on a fresh VM by calling `just rg` before the rust target `x86_64-unknown-none` is installed.
Docs: https://rust-lang.github.io/rustup/overrides.html#targets

Automatically install guest cross-compilation target if not installed

---

src/hyperlight_host/src/sandbox/host_funcs.rs
src/hyperlight_host/src/sandbox/initialized_multi_use.rs
src/hyperlight_host/src/seccomp/guest.rs
src/tests/rust_guests/simpleguest/src/main.rs

We have seen CI being flaky due to a sporatic `openat` syscall. Turns out (g)libc can try to open `/proc/sys/vm/overcommit_memory` during a call to `free()`. 
This PRs makes `openat` return `EACCES` rather than trap.
An alternative solution I tried is to "prime" malloc/free before applying the seccompfilter, but that didn't work.
Closes #175

Prevent openat from trapping on seccomp thread, by making it return EACCES instead

---

Cargo.toml
src/hyperlight_testing/Cargo.toml

In #580 a version number was adding to the hyperlight-testing dependency. This caused the Cargo pubish job for the last release to [fail](https://github.com/hyperlight-dev/hyperlight/actions/runs/15502276649/job/43652946703).
This PR removes the version number so we don't have to publish the hyperlight-testing crate

Remove version number from hyperlight-testing crate dependency

---

dev/auto-approve-dependabot.sh

Adds additional checks to the script used to validate dependabot PRs before auto approving them:
Only selects PRs that are not from forked repos and have a name starting `dependabot/cargo`
Will not approve any PRs that update files other than `Cargo.toml` or `Cargo.lock` (does not approve PRs which update GH workflows)
Does not update any PRs if there are checks which require permission to run

Add additional checks on PR before auto approving

---

.github/workflows/dep_rust.yml
Cargo.lock
Justfile
docs/how-to-debug-a-hyperlight-guest.md
src/hyperlight_host/Cargo.toml
src/hyperlight_host/build.rs
src/hyperlight_host/src/hypervisor/crashdump.rs
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/hyperv_windows.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/hypervisor/mod.rs
src/hyperlight_host/src/hypervisor/windows_hypervisor_platform.rs
src/hyperlight_host/src/sandbox/config.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
src/tests/rust_guests/witguest/Cargo.lock

- Add support for core dump file generation when a guest crashes #310 
This depends on [PR](https://github.com/microsoft/elfcore/pull/34).
This closes #310 
- The `crashdump` feature toggles the logic of the creation of core dumps for Hyperlight Sandboxes.
Additionally, core dumps can be configured at the Sandbox level. By default, all the Sandboxes have core dump generation enabled. The user can set the `guest_core_dump = false` in the `SandboxConfiguration` to disable core dumps for specific Sandboxes.
- By default, Hyperlight places the core dumps in the temporary directory (platform specific).
To change this, use the `HYPERLIGHT_CORE_DUMP_DIR` to specify a directory. If the directory does not exist, it will be created.

Support ELF core dump creation on guest crash

---

Justfile
rust-toolchain.toml
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/seccomp/guest.rs

This pull request introduces support for building with the `musl` libc target, updates syscall handling for compatibility, and adds conditional compilation for thread ID initialization. Below is a summary of the most important changes:
* Added a new `build-with-musl-libc` target in the `Justfile` to enable building with the `musl` libc target (`x86_64-unknown-linux-musl`). This includes adding the required Rust target and building with the appropriate profile.
* Updated the `LinuxInterruptHandle` initialization in `HypervLinuxDriver` to conditionally define the `tid` field based on whether the target is `musl` or not. This ensures compatibility with the `musl` libc environment.
* Applied the same conditional logic for the `tid` field in the `KVMDriver` to maintain consistency across …

Allow hyperlight-host to build with x86_64-unknown-linux-musl target

---

src/hyperlight_component_macro/src/lib.rs
src/hyperlight_component_util/src/rtypes.rs
src/tests/rust_guests/callbackguest/Cargo.lock
src/tests/rust_guests/simpleguest/Cargo.lock

This PR removes a duplicated `derive(Clone)` in `hyperlight-component-util` that result in a compilation error when using the `wasm_guest_bindgen` macro from `hyperlight-wasm`.
Clone is already being derived in L. 483

Remove duplicate derive Clone in macro

---

src/hyperlight_component_util/src/rtypes.rs
src/hyperlight_host/tests/wit_test.rs
src/tests/rust_guests/witguest/Cargo.lock

This PR removes the `Clone` and `PartialEq` requirement from `variant` and `record` wit types.
This change makes the `hyperlight-wasm-sockets-example` example work.

make socket component example work

---

src/hyperlight_common/src/mem.rs
src/hyperlight_guest/src/guest_handle/host_comm.rs
src/hyperlight_guest_bin/src/host_comm.rs
src/hyperlight_host/src/mem/layout.rs
src/hyperlight_host/src/mem/memory_region.rs
src/hyperlight_host/src/mem/mgr.rs
src/hyperlight_host/src/sandbox/mem_mgr.rs
src/hyperlight_host/src/sandbox/outb.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/tests/rust_guests/simpleguest/src/main.rs

This PR contains the following changes:
**(1)** Made a non-breaking change to the signature of the `UninitializedSandbox::new(...)` function. Now, instead of a `GuestBinary`, it takes a `GuestEnvironment`, which contains the usual binary + optional blob data.
**(2)** Created new user memory region to store the extra blob data and added some extra config options for it.
**(3)** Added info of the new memory region to the PEB.
**(4)** Added tests verifying added blob data.
Reviewing commit-by-commit might be best 👍

Added capability to load extra blob data in sandbox

---

Justfile
src/hyperlight_host/Cargo.toml
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/hyperv_windows.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/hyperlight_host/src/hypervisor/mod.rs
src/hyperlight_host/src/mem/elf.rs
src/hyperlight_host/src/mem/layout.rs
src/hyperlight_host/src/mem/memory_region.rs
src/hyperlight_host/src/mem/mgr.rs
src/hyperlight_host/src/sandbox/uninitialized_evolve.rs

This is an extra feature flag that allows disabling our paging setup (when removed). This is needed to further enable custom guests and should not impact any of our current workloads. init-paging is on by default.

[host] adds init-paging feature

---

src/hyperlight_common/src/flatbuffer_wrappers/guest_error.rs
src/hyperlight_host/src/mem/mgr.rs
src/hyperlight_host/src/mem/shared_mem.rs

Currently, 3 error records gets logged for each guest function call, successful or not. This is because the way we check if an error happened is by trying to deserialize a GuestError. If this deserialization fails (which it does in case of a successful guest function call), 3 errors gets logged.  See #497 for more info.
This PR is just a short term fix. We should not rely on this "trying to deserialize an error" for error handling. I'm leaving the linked issue open, so that we can address this properly in the future.

Don't log expected error on each guest function call

---

src/hyperlight_guest_bin/.cargo/config.toml
src/hyperlight_guest_bin/build.rs

This pull request simplifies the build process for the `hyperlight_guest_bin` by removing support for Windows-specific tools and configurations since we no longer support PE guests.

Remove support for building PE files from hyperlight-guest-bin build.rs

---

src/hyperlight_host/examples/guest-debugging/main.rs
src/hyperlight_host/src/hypervisor/hyperv_linux.rs
src/hyperlight_host/src/hypervisor/hyperv_windows.rs
src/hyperlight_host/src/hypervisor/kvm.rs
src/tests/rust_guests/witguest/Cargo.lock

This pull request addresses an issue with the `gdb` feature.
**_NOTE_**: Additionally, I have modified the `guest-debugging` example to use two sandboxes(one with debugging enabled and one without) to help find similar issues in the future.
When the `gdb` feature is turned on for `hyperlight`  and a sandbox is not configured to enable debugging, it receives `Debug not enabled` error.
This happens because of a message that is sent, during the Hypervisor construction phase, from the Hypervisor to the `gdb` thread.
The problem is that the signal is sent even if the sandbox has no debug enabled.
The transmission fails because there is no `gdb` thread to receive it and returns this error.
Add a condition before sending the signal to ensure the sandbox has debugging enabled

gdb: fix issue "Debug not enabled" when `gdb` feature was enabled

---

src/hyperlight_host/src/lib.rs
src/hyperlight_host/src/sandbox/hypervisor.rs

These `deny` lints can be annoying during local development as it prevents your code from compiling while iterating. Switching to `warn` instead shouldn't have any negative impact on quality, since clippy will still catch all warnings which will still prevent PRs from being merged.
I added (back) a compiler error if neither hypervisor feature is enabled, as that is required by a test `just test-compilation-fail`. It was removed when in-process mode was added to Linux, but never re-added when in-process mode was removed. I think it's important that this is a compiler error and not a runtime error as Hyperlight is useless without an enabled hypervisor. (At runtime the error would otherwise be surfaced as a NoHypervisorFound error)

Switch 'deny' lints to 'warn'

---

.github/workflows/dep_rust.yml
Justfile
hack/clippy-package-features.sh
src/hyperlight_guest/src/guest_handle/handle.rs
src/hyperlight_guest/src/guest_handle/host_comm.rs
src/hyperlight_guest_bin/src/exceptions/handler.rs
src/hyperlight_guest_bin/src/exceptions/idtr.rs
src/hyperlight_guest_bin/src/guest_function/call.rs
src/hyperlight_guest_bin/src/host_comm.rs
src/hyperlight_guest_bin/src/lib.rs
src/hyperlight_guest_bin/src/paging.rs

Fixes #549 
WIP - I plan to move the clippy and fmt check out of `dep_rust` so we can a) run the in parallel, and b) not need to run them for each arch/hypervisor/target matrix. Right now I just want to test that we've caught all the clippy issues

Clippy updates

---

src/hyperlight_host/src/sandbox/initialized_multi_use.rs

Hyperlight-wasm needs this here https://github.com/hyperlight-dev/hyperlight-wasm/blob/3aed4cc829cdc534d6d9928ffd3ad88f48f9d33f/src/hyperlight_wasm/src/sandbox/wasm_sandbox.rs#L65. It uses the version on the `MultiUseGuestCallContext` (which is gone now after Snapshot refactor), so we need it pub on the sandbox

Make MultiUseSandbox::map_file_cow public

---

src/hyperlight_host/src/error.rs
src/hyperlight_host/src/mem/mgr.rs
src/hyperlight_host/src/mem/shared_mem_snapshot.rs
src/hyperlight_host/src/sandbox/initialized_multi_use.rs

Requires #742
This PR makes sure sandboxes can only be restored to snapshots taken on the same sandbox. This restriction is currently needed because could cause corrupt state otherwise. We will eventually lift this restriction.
If you worry that the u64 will overflow, don't 😎

Restrict restoring sandboxes to snapshot taken on self

---

.github/workflows/CreateRelease.yml
.github/workflows/ReleaseBlockerCheck.yml
.github/workflows/ReleaseBlockerLabelCleanUp.yml
dev/check-release-blockers.sh
docs/github-labels.md

If any open issue has the label "release-blocker" don't create a release or publish crates.
Fixes #716

Adds blocker to release if any issue has release-blocker label

---

src/hyperlight_guest_bin/src/lib.rs

Do not run any complex tasks until the global allocator is initialized.

fix(guest-bin): move logger initialization

---

.github/workflows/CreateRelease.yml

Fixes insufficent permission, see here https://github.com/hyperlight-dev/hyperlight/actions/runs/16727948409

Give release-blocker-action permission to read github issues

---

Cargo.lock
src/hyperlight_host/Cargo.toml
src/hyperlight_host/src/error.rs
src/hyperlight_host/src/hypervisor/hyperv_linux.rs

Fixes a common build error which occurs when the version of vmm-sys-util crate does not match between mshv/kvm.
VmmSysError variant is now solely used for our signal registration, and is not used by mshv nor kvm code.
Kvm functions like ` Kvm::new()?` will ue the new variant automatically.
Certain Mshv functions from mshv_bindings used to use our vmm-sys-util error, which are changed in this commit.
This error only manifests when a separate crate depends on hyperlight-host, but not when we build hyperlight-host ourselves, since we check in our cargo.lock, and dependency resolution could make crates have different versions.
The error either happened in kvm code (as seen below), or in mshv code, depending on which version of vmm-sys-util hyperlight uses
```
error[E0277]: `?` couldn't …
```

Introduce a separate KVM error variant of HyperlightError.

---

.github/workflows/CargoPublish.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/tests/rust_guests/callbackguest/Cargo.lock
src/tests/rust_guests/simpleguest/Cargo.lock
typos.toml

Updates for v0.8.0 release
This pull request prepares the repository for the `v0.8.0` release, updating crate versions, changelog, and CI workflow to support new features and improvements. It introduces guest tracing support, memory mapping enhancements, and updates the publishing workflow to include new crates.
**Release preparation and versioning:**
* Updated all workspace crate versions to `0.8.0` in `Cargo.toml` to reflect the new release. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L31-R31) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L40-R48)
* Added a new section for version `v0.8.0` in `CHANGELOG.md` detailing major changes, fixes, and removals, including breaking changes to the `Callable` trait …

Updates for v0.8.0 release

---

.github/workflows/ReleaseBlockerCheck.yml

This pull request updates the release blocker check workflow to ensure that the release blocker script only runs on release branches.

fix release blocker so it only blocks on release branches

---

src/hyperlight_guest_bin/src/memory.rs

The guest allocation wrapper aligned only the total memory block but did not guarantee that the pointer returned to the user was itself properly aligned. This patch attempts to fix that.
It also adds alloc_aligned function which would be tricky to implement outside the guest but will make implementing other posix like allocation API much easier.

fix(guest-bin): align user memory allocations

---

src/hyperlight_host/src/signal_handlers/mod.rs

`setup_signal_handlers` is called once per new sandbox (this is needed due to the possibility of different sandboxes using different signal # to cancel executions). This also caused the panic hook to be set unnecessarily for each new sandbox. This PR fixes it by introducing a simple `Once`.
I confirmed locally that this fixes the long stacktraces we've been seeing, since it's non-trivial to add a test for it.
Closes #816

Fix unbounded growth of panic hook after each new sandbox

---

fuzz/fuzz_targets/host_call.rs
src/hyperlight_host/src/sandbox/initialized_multi_use.rs

This PR prevents `fuzz_host_call` from hitting a memory leak upon encountering host function calling errors. It restores to a known clean snapshot on each iteration. This fix should not be needed once #826 is fixed. 
Snapshot restore initially wasn't working in the fuzzing case due to a bug discovered by @ludfjig in `call_type_erased_guest_function_by_name` (snapshot wasn't being set to None) so this bug has been fixed. 
This PR also more explicitly ignores some expected errors that may come up from host call fuzzing.

Fixes to Host Call Fuzzing

---

Justfile
flake.nix
src/hyperlight_component_util/src/emit.rs
src/hyperlight_component_util/src/guest.rs
src/hyperlight_component_util/src/hl.rs
src/hyperlight_component_util/src/host.rs
src/hyperlight_component_util/src/rtypes.rs
src/hyperlight_host/tests/wit_test.rs
src/tests/rust_guests/witguest/Cargo.lock
src/tests/rust_guests/witguest/Cargo.toml
src/tests/rust_guests/witguest/guest.wit
src/tests/rust_guests/witguest/src/main.rs

This should fix a bunch of issues including those that #829 was getting at.

Make the component macros support passing host resources to guests

---

src/hyperlight_host/benches/benchmarks.rs
src/tests/rust_guests/witguest/Cargo.lock

KVM [docs](https://docs.kernel.org/virt/kvm/api.html) claim:
>vcpu ioctls should be issued from the same thread that was used to create the vcpu, except for asynchronous vcpu ioctl that are marked as such in the documentation. Otherwise, the first ioctl after switching threads could see a performance impact.
It would be beneficial to measure this overhead, as well as overhead on MSHV

Add benchmark for measuring performance impact on moving sandbox across thread

---

src/hyperlight_host/src/mem/layout.rs
src/hyperlight_host/src/mem/mgr.rs
src/hyperlight_host/src/mem/shared_mem.rs
src/hyperlight_host/src/mem/shared_mem_snapshot.rs
src/hyperlight_host/src/sandbox/initialized_multi_use.rs

These are all unused but seems we forgot to remove them when removing the inprocess feature

Remove old code used for removed in-process feature

---

src/hyperlight_host/benches/benchmarks.rs

Adds a benchmark which measures the time between calling `kill()` and the guest function returning. It's good to have data on this

Add benchmark for measuring time to interrupt a sandbox

---

src/hyperlight_host/src/sandbox/mod.rs
src/hyperlight_host/src/sandbox/uninitialized.rs
src/hyperlight_host/src/sandbox/uninitialized_evolve.rs

Evolving involves a transformation closure and whatnot, which just add complexity. It is not needed anymore since we only have 1 type of sandbox

Refactor evolve code to be simpler

---

.devcontainer/Dockerfile
.github/workflows/RustNightly.yml

The Dev images jumped to `trixie` in the latest release which doesn't have some packages yet. This pins to the latest stable version
This fixes the builds for the dev container: https://github.com/hyperlight-dev/hyperlight/actions/workflows/CreateDevcontainerImage.yml  
Successful run:
```
#5 [base 2/3] RUN apt-get update     && apt-get -y install         build-essential         cmake         curl         gdb         git         gnupg         gnuplot         lsb-release         make         software-properties-common         sudo         wget
#5 0.221 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#5 0.264 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#5 0.280 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#5 …
```

Pin to Debian 12 (bookworm) for Dev image and fix for Nightly
